/*
 * Copyright 2024 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export type {
  AccessRequirements,
  AddExternalResourceReferenceRequest,
  AddFilesystemResourceReferenceRequest,
  AddMarkingsRequest,
  AddOrganizationsRequest,
  AddProjectResourceReferencesRequest,
  AddResourceReferenceRequest,
  AddResourceRolesRequest,
  AddResourceTagsRequest,
  CreateFolderRequest,
  CreateProjectFromTemplateRequest,
  CreateProjectRequest,
  CreateSpaceRequest,
  Everyone,
  FileSystemId,
  Folder,
  FolderRid,
  FolderType,
  GetByPathResourcesBatchRequestElement,
  GetByPathResourcesBatchResponse,
  GetFoldersBatchRequestElement,
  GetFoldersBatchResponse,
  GetRecentlyViewedResponse,
  GetResourcesBatchRequestElement,
  GetResourcesBatchResponse,
  IsDirectlyApplied,
  ListChildrenOfFolderResponse,
  ListMarkingsOfResourceResponse,
  ListOrganizationsOfProjectResponse,
  ListProjectResourceReferencesResponse,
  ListResourceRolesResponse,
  ListResourceTagsResponse,
  ListSpacesResponse,
  Marking,
  Organization,
  PrincipalIdOnly,
  PrincipalWithId,
  Project,
  ProjectExternalResourceReference,
  ProjectFilesystemResourceReference,
  ProjectResourceLevelRoleGrantsAllowed,
  ProjectResourceReference,
  ProjectResourceReferenceType,
  ProjectResourceReferenceUnion,
  ProjectRid,
  ProjectTemplateRid,
  ProjectTemplateVariableId,
  ProjectTemplateVariableValue,
  RecentlyViewedLimit,
  RecentlyViewedResource,
  RemoveMarkingsRequest,
  RemoveOrganizationsRequest,
  RemoveProjectResourceReferencesRequest,
  RemoveResourceRolesRequest,
  RemoveResourceTagsRequest,
  ReplaceFolderRequest,
  ReplaceProjectRequest,
  ReplaceSpaceRequest,
  Resource,
  ResourceDisplayName,
  ResourcePath,
  ResourceRid,
  ResourceRole,
  ResourceRoleIdentifier,
  ResourceRolePrincipal,
  ResourceRolePrincipalIdentifier,
  ResourceTag,
  ResourceTagDisplayName,
  ResourceType,
  Space,
  SpaceMavenIdentifier,
  SpaceRid,
  TagRid,
  TrashStatus,
  UsageAccountRid,
} from "./_components.js";
export type {
  AddGroupToParentGroupPermissionDenied,
  AddMarkingsPermissionDenied,
  AddOrganizationsPermissionDenied,
  AddProjectResourceReferencesPermissionDenied,
  AddResourceRolesPermissionDenied,
  AddResourceTagsPermissionDenied,
  CircularDependency,
  CreateFolderOutsideProjectNotSupported,
  CreateFolderPermissionDenied,
  CreateGroupPermissionDenied,
  CreateProjectFromTemplatePermissionDenied,
  CreateProjectNoOwnerLikeRoleGrant,
  CreateProjectPermissionDenied,
  CreateSpacePermissionDenied,
  DefaultRolesNotInSpaceRoleSet,
  DeleteResourcePermissionDenied,
  DeleteSpacePermissionDenied,
  EnrollmentNotFound,
  FolderNotFound,
  ForbiddenOperationOnAutosavedResource,
  ForbiddenOperationOnHiddenResource,
  GetAccessRequirementsPermissionDenied,
  GetByPathPermissionDenied,
  GetRecentlyViewedPermissionDenied,
  GetRootFolderNotSupported,
  GetSpaceResourceNotSupported,
  InvalidDefaultRoles,
  InvalidDescription,
  InvalidDisplayName,
  InvalidFolder,
  InvalidOrganizationHierarchy,
  InvalidOrganizations,
  InvalidParentFolder,
  InvalidPath,
  InvalidPrincipalIdsForGroupTemplate,
  InvalidProject,
  InvalidResourceReference,
  InvalidRoleIds,
  InvalidVariable,
  InvalidVariableEnumOption,
  MarkingNotFound,
  MissingDisplayName,
  MissingVariableValue,
  NotAuthorizedToApplyOrganization,
  OrganizationCannotBeRemoved,
  OrganizationMarkingNotOnSpace,
  OrganizationMarkingNotSupported,
  OrganizationsNotFound,
  PathNotFound,
  PermanentlyDeleteResourcePermissionDenied,
  ProjectCreationNotSupported,
  ProjectNameAlreadyExists,
  ProjectNotFound,
  ProjectTemplateNotFound,
  RecentlyViewedLimitBelowMinimum,
  RemoveMarkingsPermissionDenied,
  RemoveOrganizationsPermissionDenied,
  RemoveProjectResourceReferencesPermissionDenied,
  RemoveResourceRolesPermissionDenied,
  RemoveResourceTagsPermissionDenied,
  ReplaceFolderPermissionDenied,
  ReplaceProjectPermissionDenied,
  ReplaceSpacePermissionDenied,
  ReservedSpaceCannotBeReplaced,
  ResourceNameAlreadyExists,
  ResourceNotDirectlyTrashed,
  ResourceNotFound,
  ResourceNotTrashed,
  RestoreResourcePermissionDenied,
  RoleSetNotFound,
  SpaceInternalError,
  SpaceInvalidArgument,
  SpaceNameInvalid,
  SpaceNotEmpty,
  SpaceNotFound,
  TagNotFound,
  TemplateGroupNameConflict,
  TemplateMarkingNameConflict,
  TrashingAutosavedResourcesNotSupported,
  TrashingHiddenResourcesNotSupported,
  TrashingSpaceNotSupported,
  UsageAccountServiceIsNotPresent,
} from "./_errors.js";
export * as Folders from "./public/Folder.js";
export * as Projects from "./public/Project.js";
export * as ProjectResourceReferences from "./public/ProjectResourceReference.js";
export * as Resources from "./public/Resource.js";
export * as ResourceRoles from "./public/ResourceRole.js";
export * as ResourceTags from "./public/ResourceTag.js";
export * as Spaces from "./public/Space.js";
